### ISSUE TITLE
Set up Swagger for Spring Boot using Springfox.

### ISSUE THREAD

**Issue by stephane-segning** [stephane-segning/lynx-scanner#31]

**Comment by stephane-segning** [comment]
Help yourself using this https://springdoc.org/

**Comment by nancymuyeh** [comment]
> Help yourself using this https://springdoc.org/

@stephane-segning spring boot version 3.*.* does not support springfox, can I proceed to use springdoc instead of SpringFox?

**Comment by stephane-segning** [comment]
Done in #20
